name: BobApp-Backend CI/CD pipeline

on: [push, pull_request]

env:
  BACKEND_PATH: 'back'
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'temurin'
  CACHE_MAVEN: 'maven'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.CACHE_MAVEN }}

      - name: Build with Maven
        working-directory: ${{ env.BACKEND_PATH }}
        run: mvn -B clean compile


  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.CACHE_MAVEN }}

      - name: Run tests with Maven
        working-directory: ${{ env.BACKEND_PATH }}
        run: mvn -B clean verify

      - name: Publish tests report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Back-end Tests
          working-directory: ${{ env.BACKEND_PATH }}
          path: target/surefire-reports/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: java-junit


  quality-backend:
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.BACKEND_PATH }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.CACHE_MAVEN }}

      - name: Run tests with Maven
        working-directory: ${{ env.BACKEND_PATH }}
        run: mvn -B clean verify

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ${{ env.BACKEND_PATH }}
          args: >
            -Dsonar.organization=maximedrouault
            -Dsonar.projectKey=maximedrouault_bobapp-back
            -Dsonar.java.binaries=target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}